//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IconsPath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IconsPath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.Core.Resources.IconsPath", typeof(IconsPath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/analytics.ico.
        /// </summary>
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/arrow_down.ico.
        /// </summary>
        public static string ArrowDown {
            get {
                return ResourceManager.GetString("ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/arrow_left.ico.
        /// </summary>
        public static string ArrowLeft {
            get {
                return ResourceManager.GetString("ArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/arrow_right.ico.
        /// </summary>
        public static string ArrowRight {
            get {
                return ResourceManager.GetString("ArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/arrow_up.ico.
        /// </summary>
        public static string ArrowUp {
            get {
                return ResourceManager.GetString("ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/catalog.ico.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/category.ico.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/close.ico.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/customers.ico.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard.ico.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_cancels.ico.
        /// </summary>
        public static string DashboardCancels {
            get {
                return ResourceManager.GetString("DashboardCancels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_cost.ico.
        /// </summary>
        public static string DashboardCost {
            get {
                return ResourceManager.GetString("DashboardCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_profit.ico.
        /// </summary>
        public static string DashboardProfit {
            get {
                return ResourceManager.GetString("DashboardProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_purchases.ico.
        /// </summary>
        public static string DashboardPurchases {
            get {
                return ResourceManager.GetString("DashboardPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_quantity_in_hand.ico.
        /// </summary>
        public static string DashboardQuantityInHand {
            get {
                return ResourceManager.GetString("DashboardQuantityInHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_returns.ico.
        /// </summary>
        public static string DashboardReturns {
            get {
                return ResourceManager.GetString("DashboardReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_revenue.ico.
        /// </summary>
        public static string DashboardRevenue {
            get {
                return ResourceManager.GetString("DashboardRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_sales.ico.
        /// </summary>
        public static string DashboardSales {
            get {
                return ResourceManager.GetString("DashboardSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_supplies_to_receive.ico.
        /// </summary>
        public static string DashboardSuppliesToReceive {
            get {
                return ResourceManager.GetString("DashboardSuppliesToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_total_customers.ico.
        /// </summary>
        public static string DashboardTotalCustomers {
            get {
                return ResourceManager.GetString("DashboardTotalCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dashboard_total_supplierss.ico.
        /// </summary>
        public static string DashboardTotalSuppliers {
            get {
                return ResourceManager.GetString("DashboardTotalSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/debts.ico.
        /// </summary>
        public static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dropdown.ico.
        /// </summary>
        public static string Dropdown {
            get {
                return ResourceManager.GetString("Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/dropup.ico.
        /// </summary>
        public static string Dropup {
            get {
                return ResourceManager.GetString("Dropup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/inventory.ico.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/minimize.ico.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/notifications.ico.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/production.ico.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/reports.ico.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/restore.ico.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/sale.ico.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/settings.ico.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/suppliers.ico.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory.Core;Component/Resources/Icons/supplies.ico.
        /// </summary>
        public static string Supplies {
            get {
                return ResourceManager.GetString("Supplies", resourceCulture);
            }
        }
    }
}
